"""Emit the compiler's declaration skeleton as compilable Pascal.

The deliverable is source that recompiles to Apple's p-code, and the
declarations come first: they fix every global offset, every record field
displacement and every array bound the code refers to. Getting them right is
a precondition for any procedure body being right, and unlike a procedure
body they can be checked *now* -- finding 54 sizes them, `varblock.py`
round-trips the offsets, and a compiler can be asked whether they parse.

This assembles `PROGRAM`, `CONST`, `TYPE` and `VAR` from UCSD II.0's compiler
source with the edits Apple's binary forces, each one cited. Nothing here is
invented: an edit is either a constant the binary states or a field whose
absence the binary's record sizes require.

The procedure bodies are not here. What comes out is a program whose
declarations are complete and whose body is empty, which is exactly the thing
`ucsdpsys_compile` can be pointed at to find out whether the declarations are
well formed at all.

Writes analysis/reconstruction/skeleton-{1.1,1.3}.text.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import applesrc
from varblock import build as build_vars

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "analysis" / "reconstruction"


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for ver in ("1.1", "1.3"):
        consts, types, notes = applesrc.blocks(ver)
        # The VAR block is generated separately and offset-checked; take the
        # declarations out of it and leave its commentary behind.
        varlines = [ln for ln in build_vars(ver)
                    if ln.startswith("  ") and " : " in ln]

        # The outer block is (* *) so that the { } citations inside it are
        # plain text: Pascal comments do not nest, and a { } inside a { }
        # ends the outer one at the first }.
        L = [f"(* Apple Pascal {ver} SYSTEM.COMPILER -- declaration skeleton.",
             "   Generated by tools/srcskel.py; do not edit.",
             "",
             "  CONST and TYPE are UCSD II.0's, verbatim, with these edits and",
             "  no others -- each one a number or an absence the binary states:",
             ""]
        L += [f"    {n}" for n in notes] or ["    (none)"]
        L += ["",
              "  VAR is tools/varblock.py's output, which allocates back to",
              "  Apple's own offsets under the compiler's allocation rule.",
              "  Procedure bodies are NOT here: this is the declarations only,",
              "  so that they can be compiled and checked on their own.",
              "*)",
              "",
              # No `(*$U-*)`: finding 23c shows PASCALCO.1 has lex 0, an
              # ordinary user program main, so the compiler was not built
              # with it -- unlike the operating system (finding 47).
              "PROGRAM PASCALCOMPILER;",
              "",
              "CONST" + consts.rstrip(),
              "",
              "TYPE" + types.rstrip(),
              "",
              "VAR",
              ]
        L += varlines
        L += ["", "BEGIN", "END.", ""]

        f = OUT / f"skeleton-{ver}.text"
        f.write_text("\n".join(L), encoding="ascii", errors="replace")
        print(f"[{ver}] wrote {f.name}: {len(varlines)} globals, "
              f"{len(notes)} edits to UCSD's declarations")
    return 0


if __name__ == "__main__":
    sys.exit(main())
