"""Emit the compiler's declaration skeleton as compilable Pascal.

The deliverable is source that recompiles to Apple's p-code, and the
declarations come first: they fix every global offset, every record field
displacement and every array bound the code refers to. Getting them right is
a precondition for any procedure body being right, and unlike a procedure
body they can be checked *now* -- finding 54 sizes them, `varblock.py`
round-trips the offsets, and a compiler can be asked whether they parse.

This assembles `PROGRAM`, `CONST`, `TYPE` and `VAR` from UCSD II.0's compiler
source with the edits Apple's binary forces, each one cited. Nothing here is
invented: an edit is either a constant the binary states or a field whose
absence the binary's record sizes require.

The procedure bodies are not here. What comes out is a program whose
declarations are complete and whose body is empty, which is exactly the thing
`ucsdpsys_compile` can be pointed at to find out whether the declarations are
well formed at all.

Writes analysis/reconstruction/skeleton-{1.1,1.3}.text.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import applesrc
from a2pascal.srcfmt import WIDTH, format_lines, over_width
from varblock import build as build_vars

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "analysis" / "reconstruction"


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for ver in ("1.1", "1.3"):
        consts, types, notes = applesrc.blocks(ver)
        # The VAR block is generated separately and offset-checked; take the
        # declarations out of it and leave its commentary behind.
        varlines = [ln for ln in build_vars(ver)
                    if ln.startswith("  ") and " : " in ln]

        # The two parameter words are typed pointers, and their element
        # types have to be declared in the host program: a parameter list is
        # outside the block it heads, so it cannot see that block's own TYPE
        # section. Take the bounds from the CONST block rather than repeating
        # them, so an edit to Apple's numbers cannot leave the two out of
        # step.
        def const(name: str) -> str:
            m = re.search(rf"\b{name}\s*=\s*(-?\d+)", consts)
            if not m:
                raise SystemExit(f"[{ver}] no CONST {name} to bound the "
                                 f"parameter types with")
            return m.group(1)

        maxcursor, maxcode = const("MAXCURSOR"), const("MAXCODE")

        # The outer block is (* *) so that the { } citations inside it are
        # plain text: Pascal comments do not nest, and a { } inside a { }
        # ends the outer one at the first }.
        L = [f"(* Apple Pascal {ver} SYSTEM.COMPILER -- declaration skeleton.",
             "   Generated by tools/srcskel.py; do not edit.",
             "",
             "  CONST and TYPE are UCSD II.0's, verbatim, with these edits and",
             "  no others -- each one a number or an absence the binary states:",
             ""]
        L += [f"    {n}" for n in notes] or ["    (none)"]
        L += ["",
              "  VAR is tools/varblock.py's output, which allocates back to",
              "  Apple's own offsets under the compiler's allocation rule.",
              "  Procedure bodies are NOT here: this is the declarations only,",
              "  so that they can be compiled and checked on their own.",
              "*)",
              "",
              # Finding 60: the compiler is not a PROGRAM. It is a SEGMENT
              # PROCEDURE inside a `(*$U-*)` host program, exactly as UCSD
              # II.0 has it -- which is what gives PASCALCO.1 its lex 0, its
              # segment number 1, its `SLDO`-addressed variables, and the
              # two parameter words at offsets 1 and 2 that no `VAR`
              # declaration could ever reach.
              "(*$U-*)",
              "PROGRAM PASCALSYSTEM;",
              "",
              "{ The host program declares no VARIABLES. Under (*$U-*) a",
              "  segment procedure's own variables ARE the global data",
              "  segment, laid out after its parameter words, so a variable",
              "  here would collide with the compiler's own globals. CONST",
              "  and TYPE take no storage and are safe -- and the parameter",
              "  types have to be here, because a parameter list cannot see",
              "  the TYPE block of the procedure it belongs to. These four",
              "  restate the compiler's own CODEARRAY and SYMBUFARRAY, whose",
              "  bounds are the MAXCODE and MAXCURSOR below. }",
              "",
              f"CONST MAXCURSOR = {maxcursor}; MAXCODE = {maxcode};",
              "",
              "TYPE SYMBUFARRAY = PACKED ARRAY [0..MAXCURSOR] OF CHAR;",
              "     CODEARRAY = PACKED ARRAY [0..MAXCODE] OF CHAR;",
              "     SYMBUFPTR = ^ SYMBUFARRAY;",
              "     CODEPTR = ^ CODEARRAY;",
              "",
              "{ The operating system enters segment 1 as USERPROGRAM(NIL,NIL)",
              "  -- two words of parameters, which is Apple's PARAM SIZE 4.",
              "  The compiler NEWs its own buffers into them: the binary takes",
              "  the address of both (LAO 1, LAO 2), stores to one exactly",
              "  once, and reads them 70 and 33 times. See finding 59.",
              "",
              "  CODEP is declared FIRST and lands at global 2, SYMBUFP second",
              "  and lands at global 1, because parameters are allocated in",
              "  reverse (finding 61b). GENBYTE's `SLDO 2` for CODEP^ is what",
              "  measures this, and the order it forces is UCSD II.0's own",
              "  (compglbls.text:252-253). }",
              "",
              "SEGMENT PROCEDURE PASCALCOMPILER(CODEP: CODEPTR;",
              "                                 SYMBUFP: SYMBUFPTR);",
              "",
              "CONST" + consts.rstrip(),
              "",
              "TYPE" + types.rstrip(),
              "",
              "VAR",
              ]
        L += varlines
        # The segment procedure's body, then the host program's.
        L += ["", "BEGIN", "END;", "", "BEGIN", "END.", ""]

        # Apple's tools work in 80 columns and its `.TEXT` files have no
        # tabs; the II.0 declarations carry both problems in. Wrapping only
        # moves whitespace outside strings and comments, so the compiler sees
        # the same program -- which probe_xcompile.py then confirms by
        # compiling this and requiring Apple's own frame back.
        L = format_lines(L)
        long = over_width(L)
        if long:
            raise SystemExit(
                f"[{ver}] {len(long)} lines will not fit in {WIDTH} columns "
                f"and have no break point: {long[:5]}")

        f = OUT / f"skeleton-{ver}.text"
        f.write_text("\n".join(L), encoding="ascii", errors="replace")
        print(f"[{ver}] wrote {f.name}: {len(varlines)} globals, "
              f"{len(notes)} edits to UCSD's declarations, "
              f"{len(L)} lines, all within {WIDTH} columns")
    return 0


if __name__ == "__main__":
    sys.exit(main())
