"""Emit the compiler's declaration skeleton as compilable Pascal.

The deliverable is source that recompiles to Apple's p-code, and the
declarations come first: they fix every global offset, every record field
displacement and every array bound the code refers to. Getting them right is
a precondition for any procedure body being right, and unlike a procedure
body they can be checked *now* -- finding 54 sizes them, `varblock.py`
round-trips the offsets, and a compiler can be asked whether they parse.

This assembles `PROGRAM`, `CONST`, `TYPE` and `VAR` from UCSD II.0's compiler
source with the edits Apple's binary forces, each one cited. Nothing here is
invented: an edit is either a constant the binary states or a field whose
absence the binary's record sizes require.

The procedure bodies are not here. What comes out is a program whose
declarations are complete and whose body is empty, which is exactly the thing
`ucsdpsys_compile` can be pointed at to find out whether the declarations are
well formed at all.

Writes analysis/reconstruction/skeleton-1.3.text.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import applesrc
from a2pascal.srcfmt import WIDTH, format_lines, over_width
from varblock import build as build_vars

ROOT = Path(__file__).resolve().parent.parent
GLOBALS = ROOT / "reference_source" / "ucsd_ii0" / "GLOBALS.TEXT"

# Apple's segment 0 procedure 43, which II.0's GLOBALS.TEXT does not have --
# it has COMMAND there, taking no parameters, and Apple's takes three words
# (finding 51). Every call site pushes a string's address, then 1, then that
# string's declared length, so this is its shape and not its meaning. The
# name is withheld: nothing recovers it.
OS43 = "PROCEDURE OSPROC43(VAR S: STRING; I,N: INTEGER);"


def osforwards() -> list[str]:
    """The OS's segment 0 procedures, as unresolved FORWARDs at lex -1.

    Numbering is the whole content: procedure 1 is the outer block, so the
    Nth declaration here is procedure N+1, and `CXP 0,43` needs 42 of them.
    Parameters are dropped for all but 43 -- see the comment at the call
    site in srcskel's header.
    """
    from a2pascal.syscall import segment0_signatures
    sig = segment0_signatures(GLOBALS)
    out = []
    for n in range(2, 44):
        name, _words, _isfn = sig[n]
        if n == 43:
            decl = OS43
        elif _isfn:
            # Which of these are FUNCTIONs *is* recovered -- finding 51
            # checked it against Apple's own attribute tables -- so the
            # distinction is kept even though the result type is not used.
            decl = f"FUNCTION {name[:8]}: INTEGER;"
        else:
            decl = f"PROCEDURE {name[:8]};"
        out.append(f"{decl} FORWARD;   {{ CXP 0,{n} }}")
    return out


OUT = ROOT / "analysis" / "reconstruction"


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for ver in ("1.3",):
        consts, types, notes = applesrc.blocks(ver)
        # The VAR block is generated separately and offset-checked; take the
        # declarations out of it and leave its commentary behind.
        varlines = [ln for ln in build_vars(ver)
                    if ln.startswith("  ") and " : " in ln]

        # The two parameter words are typed pointers, and their element
        # types have to be declared in the host program: a parameter list is
        # outside the block it heads, so it cannot see that block's own TYPE
        # section. Take the bounds from the CONST block rather than repeating
        # them, so an edit to Apple's numbers cannot leave the two out of
        # step.
        def const(name: str) -> str:
            m = re.search(rf"\b{name}\s*=\s*(-?\d+)", consts)
            if not m:
                raise SystemExit(f"[{ver}] no CONST {name} to bound the "
                                 f"parameter types with")
            return m.group(1)

        maxcursor, maxcode = const("MAXCURSOR"), const("MAXCODE")

        # The outer block is (* *) so that the { } citations inside it are
        # plain text: Pascal comments do not nest, and a { } inside a { }
        # ends the outer one at the first }.
        L = [f"(* Apple Pascal {ver} SYSTEM.COMPILER -- declaration skeleton.",
             "   Generated by tools/srcskel.py; do not edit.",
             "",
             "  CONST and TYPE are UCSD II.0's, verbatim, with these edits and",
             "  no others -- each one a number or an absence the binary states:",
             ""]
        L += [f"    {n}" for n in notes] or ["    (none)"]
        L += ["",
              "  VAR is tools/varblock.py's output, which allocates back to",
              "  Apple's own offsets under the compiler's allocation rule.",
              "  Procedure bodies are NOT here: this is the declarations only,",
              "  so that they can be compiled and checked on their own.",
              "*)",
              "",
              # Finding 60: the compiler is not a PROGRAM. It is a SEGMENT
              # PROCEDURE inside a `(*$U-*)` host program, exactly as UCSD
              # II.0 has it -- which is what gives PASCALCO.1 its lex 0, its
              # segment number 1, its `SLDO`-addressed variables, and the
              # two parameter words at offsets 1 and 2 that no `VAR`
              # declaration could ever reach.
              "(*$U-*)",
              "PROGRAM PASCALSYSTEM;",
              "",
              "{ The host program's variables are the OPERATING SYSTEM's",
              "  globals. Under (*$U-*) the outer block compiles at lex -1,",
              "  which is the system's own data segment, so declaring here",
              "  does not collide with the compiler's globals at lex 0 -- the",
              "  two are different segments. It is also not optional: the",
              "  compiler reaches lex -1 at ten distinct offsets, and every",
              "  one of them is accounted for by UCSD II.0's GLOBALS.TEXT",
              "  laid out from offset 1. See finding 63.",
              "",
              "  Only what the compiler actually touches is declared, in the",
              "  order and at the sizes that put those ten offsets where the",
              "  binary has them. Everything II.0 declares after USERINFO is",
              "  past the last offset the compiler reads.",
              "",
              "  The parameter types have to be here too, because a parameter",
              "  list cannot see the TYPE block of the procedure it heads.",
              "  CODEARRAY and SYMBUFARRAY restate the compiler's own, bounded",
              "  by the MAXCODE and MAXCURSOR below. }",
              "",
              f"CONST MAXCURSOR = {maxcursor}; MAXCODE = {maxcode};",
              "",
              "TYPE SYMBUFARRAY = PACKED ARRAY [0..MAXCURSOR] OF CHAR;",
              "     CODEARRAY = PACKED ARRAY [0..MAXCODE] OF CHAR;",
              "     SYMBUFPTR = ^ SYMBUFARRAY;",
              "     CODEPTR = ^ CODEARRAY;",
              "     PHYLE = FILE;",
              "     FIBP = ^ PHYLE;",
              "     INFOREC = RECORD",
              "                 WORKSYM,WORKCODE: ^ PHYLE;",
              "                 ERRSYM,ERRBLK,ERRNUM: INTEGER;",
              "                 SLOWTERM,STUPID: BOOLEAN;",
              "                 ALTMODE: CHAR",
              "               END;",
              "",
              "VAR SYSCOM: ^ INTEGER;",
              "    GFILES: ARRAY [0..5] OF FIBP;",
              "    USERINFO: INFOREC;",
              "",
              "{ The operating system's own procedures, and the reason they",
              "  are here at all: COMPOPTIONS calls one of them BY NAME.",
              "  Almost every `CXP 0,n` in the compiler is emitted for a",
              "  standard procedure -- RESET is FOPEN, WRITE is FWRITECHAR,",
              "  BLOCKREAD is FBLOCKIO -- and needs no declaration. `CXP 0,43`",
              "  is not: no standard procedure emits it, at any argument shape",
              "  (finding 79 probed all of them). It is a call to the 42nd",
              "  procedure declared at lex -1.",
              "",
              "  An unresolved FORWARD is legal under (*$U-*) and is how a",
              "  system program names the OS: it takes a segment 0 procedure",
              "  number and compiles the call, and the body it never gets is",
              "  SYSTEM.PASCAL's. Bodies here would not do -- code at lex -1",
              "  before a SEGMENT PROCEDURE is error 399, which is the same",
              "  CODEINSEG the compiler itself reports in WRITELINKERINFO.",
              "",
              "  Only the COUNT is recovered, and it is exact: the call is",
              "  procedure 43, procedure 1 is the outer block, so there are 42",
              "  of them. The NAMES are UCSD II.0's GLOBALS.TEXT in order, for",
              "  legibility and so the numbering can be read; the PARAMETERS",
              "  are dropped, because a forward that is never called and never",
              "  defined contributes nothing but its number. Number 43 is the",
              "  exception and is not II.0's: II.0 has COMMAND there, taking",
              "  nothing, and Apple's takes three words (finding 51). What it",
              "  is called and what it does are not recovered. }",
              "",
              ] + osforwards() + [
              "",
              "{ The operating system enters segment 1 as USERPROGRAM(NIL,NIL)",
              "  -- two words of parameters, which is Apple's PARAM SIZE 4.",
              "  The compiler NEWs its own buffers into them: the binary takes",
              "  the address of both (LAO 1, LAO 2), stores to one exactly",
              "  once, and reads them 70 and 33 times. See finding 59.",
              "",
              "  CODEP is declared FIRST and lands at global 2, SYMBUFP second",
              "  and lands at global 1, because parameters are allocated in",
              "  reverse (finding 61b). GENBYTE's `SLDO 2` for CODEP^ is what",
              "  measures this, and the order it forces is UCSD II.0's own",
              "  (compglbls.text:252-253). }",
              "",
              "SEGMENT PROCEDURE PASCALCOMPILER(CODEP: CODEPTR;",
              "                                 SYMBUFP: SYMBUFPTR);",
              "",
              "CONST" + consts.rstrip(),
              "",
              "TYPE" + types.rstrip(),
              "",
              "VAR",
              ]
        L += varlines
        # The segment procedure's body, then the host program's.
        L += ["", "BEGIN", "END;", "", "BEGIN", "END.", ""]

        # Apple's tools work in 80 columns and its `.TEXT` files have no
        # tabs; the II.0 declarations carry both problems in. Wrapping only
        # moves whitespace outside strings and comments, so the compiler sees
        # the same program -- which probe_xcompile.py then confirms by
        # compiling this and requiring Apple's own frame back.
        L = format_lines(L)
        long = over_width(L)
        if long:
            raise SystemExit(
                f"[{ver}] {len(long)} lines will not fit in {WIDTH} columns "
                f"and have no break point: {long[:5]}")

        f = OUT / f"skeleton-{ver}.text"
        f.write_text("\n".join(L), encoding="ascii", errors="replace")
        print(f"[{ver}] wrote {f.name}: {len(varlines)} globals, "
              f"{len(notes)} edits to UCSD's declarations, "
              f"{len(L)} lines, all within {WIDTH} columns")
    return 0


if __name__ == "__main__":
    sys.exit(main())
